version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django-app
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  # AfterInstall:
  #   - location: scripts/install_dependencies.sh    
  #     timeout: 6000
  #     runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 1000
      runas: root
  
  # BeforeInstall:
  #   - location: scripts/before_install.sh
  #     timeout: 300
  #     runas: root
  