version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django-app
hooks:
  # AfterInstall:
  #   - location: scripts/install_dependencies.sh    
  #     timeout: 6000
  #     runas: root
  ApplicationStart:
    - location: sscripts/start_server
      timeout: 300
      runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server
  #     timeout: 300
  #     runas: root
  # BeforeInstall:
  #   - location: scripts/before_install.sh
  #     timeout: 300
  #     runas: root
  
# BeforeInstall:
#     - location: clean_instance.sh
#       timeout: 6000
#       runas: root
#   AfterInstall:
#     - location: install_os_dependencies.sh    
#       timeout: 6000
#       runas: root
#     - location: install_python_dependencies.sh
#       timeout: 6000
#       runas: ubuntu
 
