version: "3.7"

services:
  web_backend:
    build:
      context: .
    # command: gunicorn aws.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - .:/home/aws
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - gifty-backend

networks:
  gifty-backend:
    driver: bridge

volumes:
  static_volume:
  media_volume:
