#!/bin/bash

sudo apt update
sudo apt -y upgrade

# Destination folder
cd /home/ubuntu
# AWS CLI needed to get parameters
sudo apt install -y awscli

sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt install -y python3.8 python3.8-dev python3.8-venv
python3.9 -m ensurepip --default-pip --user

# My dependencies
sudo apt install -y build-essential libpq-dev gettext
# We're going to create a virtual environment to not screw up default packages
python3.8 -m venv venv
source venv/bin/activate
pip install --upgrade pip setuptools wheel
pip install -r requirements/production.txt
# ------------------------------------------------------------------------------------
