name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-20.04
    steps:
      - name: Update
        run: sudo apt update
      - name: Checkout Repository code
        uses: actions/checkout@v2
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run django unit test
        run: python3 manage.py test
  deploy:
    needs: build
    name: Run deployment
    runs-on: ubuntu-20.04
    steps:
    
      - name: Set aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name django_app \
          --deployment-group-name django_app_group \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
          